In [1]:
import numpy as np 


In [2]:
a = np.array([True, False, True])

In [3]:
np.any(a)

True

In [4]:
np.all(a)

False

In [5]:
b = 2

In [6]:
np.any(b== 2)

True

In [7]:
c = np.array([1,2,4])
print("Is the content of array c is greater than o or not",c>0)
print("Is the content of array c is less than 0 or not",c<0)

Is the content of array c is greater than o or not [ True  True  True]
Is the content of array c is less than 0 or not [False False False]


In [8]:
np.all(c>0)

True

In [9]:
np.all(c<0)

False

In [10]:
x = np.array([1,2,3])
y = np.array([4,5,6])
z = np.array([7,8,9])

#x<y<z
res1 = x<y
res1

array([ True,  True,  True])

In [11]:
res2 = y<z
res2

array([ True,  True,  True])

In [12]:
res3 = res1 & res2
res3

array([ True,  True,  True])

In [13]:
np.all(res3)

True