In [1]:
import numpy as np

In [2]:
a = np.array([12,45,36,78])
b = np.array([12,45,3,7])

In [3]:
mask = (a==b)

In [4]:
a[mask]

array([12, 45])

In [5]:
np.array_equal(a,b)

False

In [6]:
### LOgical operations 
c = np.array([1,0,0,1])
d = np.array([1,0,1,0])

In [7]:
np.logical_and(c,d)


array([ True, False, False, False])

In [8]:
np.logical_or(c,d)

array([ True, False,  True,  True])